---
language: php

php:
  - 5.3

notifications:
  email: false
  slack:
    secure: U9WociTUzfzCZIWpYUyf2W4Jc+Ek4DBC0Dm7v+jr9zDTwevyRsglKerrkfgaCgDPP18Ma+j2ANEyPf25HRReJdOmSi02H5PTtcT2DnXUanr8REklrznbXADwayEjN32vArywqRrUq94GioDY3bKXgWve61wt/4YsQMTwZjL09AQ=

script:
  - phpunit --coverage-clover build/logs/clover.xml

before_script:
  - mkdir -p build/logs
  - composer install --dev
  - mysql -e 'create database `test-jam-auth`;'
  - mysql test-jam-auth < tests/database/structure/mysql.sql

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
